# Generated by Django 4.2.4 on 2023-09-02 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_equipe', models.CharField(max_length=50)),
                ('pilotos', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pilotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_piloto1', models.CharField(max_length=50)),
                ('nome_piloto2', models.CharField(max_length=50)),
                ('equipe', models.CharField(max_length=50)),
                ('numero_carro1', models.IntegerField()),
                ('numero_carro2', models.IntegerField()),
            ],
        ),
    ]
