# Generated by Django 4.2.4 on 2023-09-02 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f1_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='pilotos',
        ),
        migrations.AlterField(
            model_name='pilotos',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1_app.equipe'),
        ),
    ]
