# Generated by Django 4.2.4 on 2023-09-02 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('f1_app', '0002_remove_equipe_pilotos_alter_pilotos_equipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pilotos',
            old_name='nome_piloto1',
            new_name='nome_do_primeiro_piloto',
        ),
        migrations.RenameField(
            model_name='pilotos',
            old_name='nome_piloto2',
            new_name='nome_do_segundo_piloto',
        ),
        migrations.RenameField(
            model_name='pilotos',
            old_name='numero_carro1',
            new_name='numero_do_carro_1',
        ),
        migrations.RenameField(
            model_name='pilotos',
            old_name='numero_carro2',
            new_name='numero_do_carro_2',
        ),
        migrations.AlterField(
            model_name='pilotos',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piloto_equipe', to='f1_app.equipe'),
        ),
    ]
