# Generated by Django 4.2.4 on 2023-09-07 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f1_app', '0003_rename_nome_piloto1_pilotos_nome_do_primeiro_piloto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipe',
            old_name='pais',
            new_name='pais_sede',
        ),
    ]
